sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(resolve:SENTRY_ENV)%'
        release: '%env(resolve:SENTRY_RELEASE)%'

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::WARNING
            hub_id: Sentry\State\HubInterface
